#!/bin/bash
#
# Usage:
#   1) Save this file as ~/.bash/prompt
#   2) Add the following line to the end of your ~/.bash_rc, ~/.bash_profile or ~/.profile:
#           . $HOME/.bash/prompt
#
# Adapted from:
#   https://gist.github.com/insin/1425703
#   https://github.com/techbelly/dotfiles/blob/master/bash/prompt

         RED="\[\033[0;31m\]"
   LIGHT_RED="\[\033[1;31m\]"
       GREEN="\[\033[0;32m\]"
 LIGHT_GREEN="\[\033[1;32m\]"
      YELLOW="\[\033[0;33m\]"
LIGHT_YELLOW="\[\033[1;33m\]"
        BLUE="\[\033[0;34m\]"
  LIGHT_BLUE="\[\033[1;34m\]"
        GRAY="\[\033[1;30m\]"
  LIGHT_GRAY="\[\033[0;37m\]"
       WHITE="\[\033[1;37m\]"
  COLOR_NONE="\[\033[0m\]"

function set_git_prompt() {
    # Check we're in a git repository.
    if `git rev-parse`; then
        # Set color based on clean/staged/dirty.
        if `git diff-index --quiet HEAD`; then
            state=${LIGHT_GREEN}
        elif `git diff-files --quiet`; then
            state=${LIGHT_YELLOW}
        else
            state=${LIGHT_RED}
        fi

        # Get the name of the branch.
        branch=`git rev-parse --abbrev-ref HEAD`

        # Set arrow icon based on status against remote.
        ahead=false
        remote=""
        if [ `git rev-list @{u}..HEAD --count` -gt 0 ]; then
            ahead=true
            remote="↑"
        fi

        if [ `git rev-list HEAD..@{u} --count` -gt 0 ]; then
            if $ahead; then
                remote="↕"
            else
                remote="↓"
            fi
        fi

        # Set the final branch string.
        GIT_PROMPT="${state}(${branch})${remote}${COLOR_NONE} "
    else
        GIT_PROMPT=""
    fi
}

# Set the prompt.
function set_prompt() {
    previous_return_value=$?;

    if [ -n "$VIRTUAL_ENV" ]; then
        venv="(`basename \"$VIRTUAL_ENV\"`)"
    else
        venv=""
    fi

    if [ -n "$SSH_CLIENT" ]; then
        prompt="${TITLEBAR}\u@\h ${LIGHT_GRAY}\w${COLOR_NONE}"
    else
        prompt="${TITLEBAR}${LIGHT_GRAY}\w${COLOR_NONE}"
    fi

    set_git_prompt

    if [ $previous_return_value == 0 ]; then
        PS1="${venv}${debian_chroot:+($debian_chroot)}${LIGHT_GREEN}∆ ${COLOR_NONE}${prompt} ${GIT_PROMPT}${LIGHT_GREEN}\$${COLOR_NONE} "
    else
        PS1="${venv}${debian_chroot:+($debian_chroot)}${LIGHT_RED}∇ ${COLOR_NONE}${prompt} ${GIT_PROMPT}${LIGHT_RED}\$${COLOR_NONE} "
    fi
}

PROMPT_COMMAND=set_prompt
